trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Use your self-hosted Linux agent pool

jobs:
- job: FetchSignInLogs
  displayName: "Fetch latest sign-in logs from Microsoft Graph"
  steps:
  - script: |
      pwsh --version
    displayName: "Check PowerShell Core version"

  - script: |
      pwsh ./Get-SignInLogs.ps1
    displayName: "Run Sign-In Log Script"
    env:
      TenantId: $(TenantId)
      ClientId: $(ClientId)
      ClientSecret: $(ClientSecret)
