trigger:
- main

pool:
  name: Default  # or your self-hosted Linux agent pool

variables:
  TenantId: $(TenantId)
  ClientId: $(ClientId)
  ClientSecret: $(ClientSecret)

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'Get-SignInLogs.ps1'
    pwsh: true
    env:
      TenantId: $(TenantId)
      ClientId: $(ClientId)
      ClientSecret: $(ClientSecret)
